apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: monitoring
  namespace: argocd

spec:
  project: default

  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: 72.6.2

    helm:
      skipCrds: false

      releaseName: monitoring
      values: |
        grafana:
          adminPassword: admin123
          persistence:
            enabled: false

        prometheus:
          prometheusSpec:
            retention: 7d
            retentionSize: "8GB"
            storageSpec: null

            resources:
              requests:
                cpu: 200m
                memory: 700Mi
              limits:
                cpu: 500m
                memory: 1Gi

        alertmanager:
          alertmanagerSpec:
            storage: null

        kubeStateMetrics:
          resources:
            requests:
              cpu: 50m
              memory: 64Mi

        prometheusOperator:
          resources:
            requests:
              cpu: 100m
              memory: 128Mi

        nodeExporter:
          enabled: true

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true
