grafana:
  service:
    type: NodePort
    nodePort: 31070

  nodeSelector:
    node-role.kubernetes.io/control-plane: ""
  tolerations:
    - key: "node-role.kubernetes.io/control-plane"
      operator: "Exists"
      effect: "NoSchedule"

prometheusOperator:
  nodeSelector:
    node-role.kubernetes.io/control-plane: ""
  tolerations:
    - key: "node-role.kubernetes.io/control-plane"
      operator: "Exists"
      effect: "NoSchedule"

kube-state-metrics:
  nodeSelector:
    node-role.kubernetes.io/control-plane: ""
  tolerations:
    - key: "node-role.kubernetes.io/control-plane"
      operator: "Exists"
      effect: "NoSchedule"

prometheus:
  service:
    type: NodePort
    nodePort: 32647

  prometheusSpec:
    nodeSelector:
      node-role.kubernetes.io/control-plane: ""
    tolerations:
      - key: "node-role.kubernetes.io/control-plane"
        operator: "Exists"
        effect: "NoSchedule"

alertmanager:
  service:
    type: NodePort
    nodePort: 30642

  config:
    global:
      smtp_smarthost: "smtp.gmail.com:587"
      smtp_from: "parikshitch02@gmail.com"
      smtp_auth_username: "parikshitch02@gmail.com"
      smtp_auth_password: "azlfjemakdjxjrtf"
      smtp_require_tls: true

    route:
      receiver: email
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 1h

    receivers:
      - name: email
        email_configs:
          - to: "parikshitch02@gmail.com"
            send_resolved: true

    inhibit_rules:
      - source_matchers:
          - severity="critical"
        target_matchers:
          - severity=~"warning|info"
        equal:
          - namespace
          - alertname

    templates:
      - "/etc/alertmanager/config/*.tmpl"

  alertmanagerSpec:
    nodeSelector:
      node-role.kubernetes.io/control-plane: ""

    tolerations:
      - key: "node-role.kubernetes.io/control-plane"
        operator: "Exists"
        effect: "NoSchedule"

 
