apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: test-alert
  namespace: monitoring

spec:
  groups:

  - name: test-alerts

    rules:

    - alert: TestEmailAlert

      expr: vector(1)

      for: 1m

      labels:
        severity: critical

      annotations:
        summary: "Test Email Alert"

        description: "This is a test alert from Prometheus."
